Update slug and track id regexes
exercism/legacy-docs pull request #41
Opened 2017-05-29 21:09 UTC by stkent

New regex disallows:

* `hello-world-` (trailing dash)
* `hello--world` (multiple consecutive dashes)
* `-hello-world` (leading dash)

2017-05-29 21:18 UTC, kytrinyx approved these changes

2017-05-29 21:33 UTC, Insti commented
I think the simpler regex is fine and that there is nothing wrong with the slugs you want to disallow, just don't choose to use them when naming problems.

`lkfjsagjsdljglj-fkgljlgjlfj-sgfgfg` is also a valid slug by the new regex, that one would hopefully also not choose use.

2017-05-29 21:35 UTC, kytrinyx commented
Hm, yeah, I think @Insti has a point. The regexes are for illustrative purposes only, to say "all lowercase with hyphens as a separator".

2017-05-29 21:35 UTC, Insti requested changes
Keep it the way it was.
(Or use the English language description)

Edit: I appreciate the intention behind the PR and am glad you made it :heart:

2017-05-29 21:39 UTC, kytrinyx commented
I think it would make sense to use the English-language description, so that we're clear that this is not a technical specification.

2017-05-29 21:43 UTC, Insti commented
Maybe add the definition under an entry for `unique identifier` or something so it doesn't need to be defined twice.

2017-05-29 22:16 UTC, stkent commented
> I think it would make sense to use the English-language description, so that we're clear that this is not a technical specification.

I agree with this; eliminating the regex altogether will result in greater clarity 👍

2017-05-29 22:20 UTC, stkent commented
Updated; what do folks think of that written description?

(Also happy to resolve conflicts if #42 is merged before this PR.)

2017-05-29 23:49 UTC, kytrinyx commented
@stkent I like how this turned out.

2017-05-30 06:07 UTC, Insti approved these changes

2017-05-30 06:49 UTC, ErikSchierboom approved these changes

2017-06-02 02:29 UTC, merged

2017-06-02 02:29 UTC, kytrinyx commented
Thank you so much, @stkent!